package calliescrimble.picturesque.datagen;

import calliescrimble.picturesque.block.ModBlocks;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class ModLootTableProvider extends FabricBlockLootTableProvider {
    public ModLootTableProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {

        addDrop(ModBlocks.ASPEN_STAIRS);
        addDrop(ModBlocks.ASPEN_SLAB, slabDrops(ModBlocks.ASPEN_SLAB));
        addDrop(ModBlocks.ASPEN_BUTTON);
        addDrop(ModBlocks.ASPEN_PRESSURE_PLATE);
        addDrop(ModBlocks.ASPEN_FENCE);
        addDrop(ModBlocks.ASPEN_FENCE_GATE);
        addDrop(ModBlocks.ASPEN_DOOR, doorDrops(ModBlocks.ASPEN_DOOR));
        addDrop(ModBlocks.ASPEN_TRAPDOOR);
        addDrop(ModBlocks.ASPEN_LOG);
        addDrop(ModBlocks.ASPEN_WOOD);
        addDrop(ModBlocks.STRIPPED_ASPEN_LOG);
        addDrop(ModBlocks.STRIPPED_ASPEN_WOOD);
        addDrop(ModBlocks.ASPEN_PLANKS);
        addDrop(ModBlocks.ASPEN_SAPLING);
        addPottedPlantDrops(ModBlocks.ASPEN_SAPLING_POT);
        addDrop(ModBlocks.ASPEN_LEAVES, leavesDrops(ModBlocks.ASPEN_LEAVES, ModBlocks.ASPEN_SAPLING, 0.0625f));
        addDrop(ModBlocks.ASPEN_SHELF);
        addDrop(ModBlocks.ASPEN_SIGN);
        addDrop(ModBlocks.ASPEN_HANGING_SIGN);

        addDrop(ModBlocks.OAK_HERRINGBONE);
        addDrop(ModBlocks.SPRUCE_HERRINGBONE);
        addDrop(ModBlocks.BIRCH_HERRINGBONE);
        addDrop(ModBlocks.JUNGLE_HERRINGBONE);
        addDrop(ModBlocks.ACACIA_HERRINGBONE);
        addDrop(ModBlocks.DARK_OAK_HERRINGBONE);
        addDrop(ModBlocks.MANGROVE_HERRINGBONE);
        addDrop(ModBlocks.CHERRY_HERRINGBONE);
        addDrop(ModBlocks.PALE_OAK_HERRINGBONE);
        addDrop(ModBlocks.BAMBOO_HERRINGBONE);
        addDrop(ModBlocks.CRIMSON_HERRINGBONE);
        addDrop(ModBlocks.WARPED_HERRINGBONE);
        addDrop(ModBlocks.ASPEN_HERRINGBONE);

        addDrop(ModBlocks.OAK_MOSAIC);
        addDrop(ModBlocks.SPRUCE_MOSAIC);
        addDrop(ModBlocks.BIRCH_MOSAIC);
        addDrop(ModBlocks.JUNGLE_MOSAIC);
        addDrop(ModBlocks.ACACIA_MOSAIC);
        addDrop(ModBlocks.DARK_OAK_MOSAIC);
        addDrop(ModBlocks.MANGROVE_MOSAIC);
        addDrop(ModBlocks.CHERRY_MOSAIC);
        addDrop(ModBlocks.PALE_OAK_MOSAIC);
        addDrop(ModBlocks.CRIMSON_MOSAIC);
        addDrop(ModBlocks.WARPED_MOSAIC);
        addDrop(ModBlocks.ASPEN_MOSAIC);
        addDrop(ModBlocks.OAK_MOSAIC_STAIRS);
        addDrop(ModBlocks.SPRUCE_MOSAIC_STAIRS);
        addDrop(ModBlocks.BIRCH_MOSAIC_STAIRS);
        addDrop(ModBlocks.JUNGLE_MOSAIC_STAIRS);
        addDrop(ModBlocks.ACACIA_MOSAIC_STAIRS);
        addDrop(ModBlocks.DARK_OAK_MOSAIC_STAIRS);
        addDrop(ModBlocks.MANGROVE_MOSAIC_STAIRS);
        addDrop(ModBlocks.CHERRY_MOSAIC_STAIRS);
        addDrop(ModBlocks.PALE_OAK_MOSAIC_STAIRS);
        addDrop(ModBlocks.CRIMSON_MOSAIC_STAIRS);
        addDrop(ModBlocks.WARPED_MOSAIC_STAIRS);
        addDrop(ModBlocks.ASPEN_MOSAIC_STAIRS);
        addDrop(ModBlocks.OAK_MOSAIC_SLAB, slabDrops(ModBlocks.OAK_MOSAIC_SLAB));
        addDrop(ModBlocks.SPRUCE_MOSAIC_SLAB, slabDrops(ModBlocks.SPRUCE_MOSAIC_SLAB));
        addDrop(ModBlocks.BIRCH_MOSAIC_SLAB, slabDrops(ModBlocks.BIRCH_MOSAIC_SLAB));
        addDrop(ModBlocks.JUNGLE_MOSAIC_SLAB, slabDrops(ModBlocks.JUNGLE_MOSAIC_SLAB));
        addDrop(ModBlocks.ACACIA_MOSAIC_SLAB, slabDrops(ModBlocks.ACACIA_MOSAIC_SLAB));
        addDrop(ModBlocks.DARK_OAK_MOSAIC_SLAB, slabDrops(ModBlocks.DARK_OAK_MOSAIC_SLAB));
        addDrop(ModBlocks.MANGROVE_MOSAIC_SLAB, slabDrops(ModBlocks.MANGROVE_MOSAIC_SLAB));
        addDrop(ModBlocks.CHERRY_MOSAIC_SLAB, slabDrops(ModBlocks.CHERRY_MOSAIC_SLAB));
        addDrop(ModBlocks.PALE_OAK_MOSAIC_SLAB, slabDrops(ModBlocks.PALE_OAK_MOSAIC_SLAB));
        addDrop(ModBlocks.CRIMSON_MOSAIC_SLAB, slabDrops(ModBlocks.CRIMSON_MOSAIC_SLAB));
        addDrop(ModBlocks.WARPED_MOSAIC_SLAB, slabDrops(ModBlocks.WARPED_MOSAIC_SLAB));
        addDrop(ModBlocks.ASPEN_MOSAIC_SLAB, slabDrops(ModBlocks.ASPEN_MOSAIC_SLAB));

        addDrop(ModBlocks.WHITE_BRICKS);
        addDrop(ModBlocks.WHITE_BRICK_STAIRS);
        addDrop(ModBlocks.WHITE_BRICK_SLAB, slabDrops(ModBlocks.WHITE_BRICK_SLAB));
        addDrop(ModBlocks.WHITE_BRICK_WALL);
        addDrop(ModBlocks.LIGHT_GRAY_BRICKS);
        addDrop(ModBlocks.LIGHT_GRAY_BRICK_STAIRS);
        addDrop(ModBlocks.LIGHT_GRAY_BRICK_SLAB, slabDrops(ModBlocks.LIGHT_GRAY_BRICK_SLAB));
        addDrop(ModBlocks.LIGHT_GRAY_BRICK_WALL);
        addDrop(ModBlocks.GRAY_BRICKS);
        addDrop(ModBlocks.GRAY_BRICK_STAIRS);
        addDrop(ModBlocks.GRAY_BRICK_SLAB, slabDrops(ModBlocks.GRAY_BRICK_SLAB));
        addDrop(ModBlocks.GRAY_BRICK_WALL);
        addDrop(ModBlocks.BLACK_BRICKS);
        addDrop(ModBlocks.BLACK_BRICK_STAIRS);
        addDrop(ModBlocks.BLACK_BRICK_SLAB, slabDrops(ModBlocks.BLACK_BRICK_SLAB));
        addDrop(ModBlocks.BLACK_BRICK_WALL);
        addDrop(ModBlocks.BROWN_BRICKS);
        addDrop(ModBlocks.BROWN_BRICK_STAIRS);
        addDrop(ModBlocks.BROWN_BRICK_SLAB, slabDrops(ModBlocks.BROWN_BRICK_SLAB));
        addDrop(ModBlocks.BROWN_BRICK_WALL);
        addDrop(ModBlocks.RED_BRICKS);
        addDrop(ModBlocks.RED_BRICK_STAIRS);
        addDrop(ModBlocks.RED_BRICK_SLAB, slabDrops(ModBlocks.RED_BRICK_SLAB));
        addDrop(ModBlocks.RED_BRICK_WALL);
        addDrop(ModBlocks.ORANGE_BRICKS);
        addDrop(ModBlocks.ORANGE_BRICK_STAIRS);
        addDrop(ModBlocks.ORANGE_BRICK_SLAB, slabDrops(ModBlocks.ORANGE_BRICK_SLAB));
        addDrop(ModBlocks.ORANGE_BRICK_WALL);
        addDrop(ModBlocks.YELLOW_BRICKS);
        addDrop(ModBlocks.YELLOW_BRICK_STAIRS);
        addDrop(ModBlocks.YELLOW_BRICK_SLAB, slabDrops(ModBlocks.YELLOW_BRICK_SLAB));
        addDrop(ModBlocks.YELLOW_BRICK_WALL);
        addDrop(ModBlocks.LIME_BRICKS);
        addDrop(ModBlocks.LIME_BRICK_STAIRS);
        addDrop(ModBlocks.LIME_BRICK_SLAB, slabDrops(ModBlocks.LIME_BRICK_SLAB));
        addDrop(ModBlocks.LIME_BRICK_WALL);
        addDrop(ModBlocks.GREEN_BRICKS);
        addDrop(ModBlocks.GREEN_BRICK_STAIRS);
        addDrop(ModBlocks.GREEN_BRICK_SLAB, slabDrops(ModBlocks.GREEN_BRICK_SLAB));
        addDrop(ModBlocks.GREEN_BRICK_WALL);
        addDrop(ModBlocks.CYAN_BRICKS);
        addDrop(ModBlocks.CYAN_BRICK_STAIRS);
        addDrop(ModBlocks.CYAN_BRICK_SLAB, slabDrops(ModBlocks.CYAN_BRICK_SLAB));
        addDrop(ModBlocks.CYAN_BRICK_WALL);
        addDrop(ModBlocks.LIGHT_BLUE_BRICKS);
        addDrop(ModBlocks.LIGHT_BLUE_BRICK_STAIRS);
        addDrop(ModBlocks.LIGHT_BLUE_BRICK_SLAB, slabDrops(ModBlocks.LIGHT_BLUE_BRICK_SLAB));
        addDrop(ModBlocks.LIGHT_BLUE_BRICK_WALL);
        addDrop(ModBlocks.BLUE_BRICKS);
        addDrop(ModBlocks.BLUE_BRICK_STAIRS);
        addDrop(ModBlocks.BLUE_BRICK_SLAB, slabDrops(ModBlocks.BLUE_BRICK_SLAB));
        addDrop(ModBlocks.BLUE_BRICK_WALL);
        addDrop(ModBlocks.PURPLE_BRICKS);
        addDrop(ModBlocks.PURPLE_BRICK_STAIRS);
        addDrop(ModBlocks.PURPLE_BRICK_SLAB, slabDrops(ModBlocks.PURPLE_BRICK_SLAB));
        addDrop(ModBlocks.PURPLE_BRICK_WALL);
        addDrop(ModBlocks.MAGENTA_BRICKS);
        addDrop(ModBlocks.MAGENTA_BRICK_STAIRS);
        addDrop(ModBlocks.MAGENTA_BRICK_SLAB, slabDrops(ModBlocks.MAGENTA_BRICK_SLAB));
        addDrop(ModBlocks.MAGENTA_BRICK_WALL);
        addDrop(ModBlocks.PINK_BRICKS);
        addDrop(ModBlocks.PINK_BRICK_STAIRS);
        addDrop(ModBlocks.PINK_BRICK_SLAB, slabDrops(ModBlocks.PINK_BRICK_SLAB));
        addDrop(ModBlocks.PINK_BRICK_WALL);

        addDrop(ModBlocks.WHITE_CHERRY_SAPLING);
        addPottedPlantDrops(ModBlocks.WHITE_CHERRY_SAPLING_POT);
        addDrop(ModBlocks.WHITE_CHERRY_LEAVES, leavesDrops(ModBlocks.WHITE_CHERRY_LEAVES, ModBlocks.WHITE_CHERRY_SAPLING, 0.0625f));

        addDrop(ModBlocks.OAK_LEAF_PILE);
        addDrop(ModBlocks.SPRUCE_LEAF_PILE);
        addDrop(ModBlocks.BIRCH_LEAF_PILE);
        addDrop(ModBlocks.ASPEN_LEAF_PILE);
        addDrop(ModBlocks.JUNGLE_LEAF_PILE);
        addDrop(ModBlocks.ACACIA_LEAF_PILE);
        addDrop(ModBlocks.DARK_OAK_LEAF_PILE);
        addDrop(ModBlocks.MANGROVE_LEAF_PILE);
        addDrop(ModBlocks.AZALEA_LEAF_PILE);
        addDrop(ModBlocks.FLOWERING_AZALEA_LEAF_PILE);
        addDrop(ModBlocks.CHERRY_LEAF_PILE);
        addDrop(ModBlocks.WHITE_CHERRY_LEAF_PILE);
        addDrop(ModBlocks.PALE_OAK_LEAF_PILE);

        addDrop(ModBlocks.CALCITE_STAIRS);
        addDrop(ModBlocks.SMOOTH_BASALT_STAIRS);
        addDrop(ModBlocks.CALCITE_SLAB, slabDrops(ModBlocks.CALCITE_SLAB));
        addDrop(ModBlocks.SMOOTH_BASALT_SLAB, slabDrops(ModBlocks.SMOOTH_BASALT_SLAB));
        addDrop(ModBlocks.CALCITE_WALL);
        addDrop(ModBlocks.SMOOTH_BASALT_WALL);
        addDrop(ModBlocks.CALCITE_BRICKS);
        addDrop(ModBlocks.CALCITE_TILES);
        addDrop(ModBlocks.CHISELED_CALCITE_BRICKS);
        addDrop(ModBlocks.SMOOTH_BASALT_BRICKS);
        addDrop(ModBlocks.CALCITE_BRICK_STAIRS);
        addDrop(ModBlocks.CALCITE_TILE_STAIRS);
        addDrop(ModBlocks.SMOOTH_BASALT_BRICK_STAIRS);
        addDrop(ModBlocks.CALCITE_BRICK_SLAB, slabDrops(ModBlocks.CALCITE_BRICK_SLAB));
        addDrop(ModBlocks.CALCITE_TILE_SLAB, slabDrops(ModBlocks.CALCITE_TILE_SLAB));
        addDrop(ModBlocks.SMOOTH_BASALT_BRICK_SLAB, slabDrops(ModBlocks.SMOOTH_BASALT_BRICK_SLAB));
        addDrop(ModBlocks.CALCITE_BRICK_WALL);
        addDrop(ModBlocks.CALCITE_TILE_WALL);
        addDrop(ModBlocks.SMOOTH_BASALT_BRICK_WALL);
        addDrop(ModBlocks.POLISHED_GRANITE_WALL);
        addDrop(ModBlocks.POLISHED_DIORITE_WALL);
        addDrop(ModBlocks.POLISHED_ANDESITE_WALL);
        addDrop(ModBlocks.POLISHED_GRANITE_BRICKS);
        addDrop(ModBlocks.POLISHED_GRANITE_BRICK_STAIRS);
        addDrop(ModBlocks.POLISHED_GRANITE_BRICK_SLAB, slabDrops(ModBlocks.POLISHED_GRANITE_BRICK_SLAB));
        addDrop(ModBlocks.POLISHED_GRANITE_BRICK_WALL);
        addDrop(ModBlocks.POLISHED_DIORITE_BRICKS);
        addDrop(ModBlocks.POLISHED_DIORITE_BRICK_STAIRS);
        addDrop(ModBlocks.POLISHED_DIORITE_BRICK_SLAB, slabDrops(ModBlocks.POLISHED_DIORITE_BRICK_SLAB));
        addDrop(ModBlocks.POLISHED_DIORITE_BRICK_WALL);
        addDrop(ModBlocks.POLISHED_ANDESITE_BRICKS);
        addDrop(ModBlocks.POLISHED_ANDESITE_BRICK_STAIRS);
        addDrop(ModBlocks.POLISHED_ANDESITE_BRICK_SLAB, slabDrops(ModBlocks.POLISHED_ANDESITE_BRICK_SLAB));
        addDrop(ModBlocks.POLISHED_ANDESITE_BRICK_WALL);
        addDrop(ModBlocks.MARIGOLD);
        addPottedPlantDrops(ModBlocks.MARIGOLD_POT);
        addDrop(ModBlocks.VIOLET_HEATHER);
        addDrop(ModBlocks.MAUVE_HEATHER);
        addDrop(ModBlocks.WHITE_HEATHER);
        addDrop(ModBlocks.AMETHYST_STAIRS);
        addDrop(ModBlocks.AMETHYST_SLAB, slabDrops(ModBlocks.AMETHYST_SLAB));
        addDrop(ModBlocks.AMETHYST_WALL);
        addDrop(ModBlocks.REDSTONE_LANTERN);
        addDrop(ModBlocks.CALLIE_PLUSHIE);
        addDrop(ModBlocks.CYNTHIA_PLUSHIE);

    }

}