package calliescrimble.picturesque.datagen;

import calliescrimble.picturesque.block.ModBlocks;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootSubProvider;
import net.minecraft.core.HolderLookup;
import java.util.concurrent.CompletableFuture;

public class ModLootTableProvider extends FabricBlockLootSubProvider {
    public ModLootTableProvider(FabricPackOutput dataOutput, CompletableFuture<HolderLookup.Provider> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {

        dropSelf(ModBlocks.ASPEN_STAIRS);
        add(ModBlocks.ASPEN_SLAB, createSlabItemTable(ModBlocks.ASPEN_SLAB));
        dropSelf(ModBlocks.ASPEN_BUTTON);
        dropSelf(ModBlocks.ASPEN_PRESSURE_PLATE);
        dropSelf(ModBlocks.ASPEN_FENCE);
        dropSelf(ModBlocks.ASPEN_FENCE_GATE);
        add(ModBlocks.ASPEN_DOOR, createDoorTable(ModBlocks.ASPEN_DOOR));
        dropSelf(ModBlocks.ASPEN_TRAPDOOR);
        dropSelf(ModBlocks.ASPEN_LOG);
        dropSelf(ModBlocks.ASPEN_WOOD);
        dropSelf(ModBlocks.STRIPPED_ASPEN_LOG);
        dropSelf(ModBlocks.STRIPPED_ASPEN_WOOD);
        dropSelf(ModBlocks.ASPEN_PLANKS);
        dropSelf(ModBlocks.ASPEN_SAPLING);
        dropPottedContents(ModBlocks.ASPEN_SAPLING_POT);
        add(ModBlocks.ASPEN_LEAVES, createLeavesDrops(ModBlocks.ASPEN_LEAVES, ModBlocks.ASPEN_SAPLING, 0.0625f));
        dropSelf(ModBlocks.ASPEN_SHELF);
        dropSelf(ModBlocks.ASPEN_SIGN);
        dropSelf(ModBlocks.ASPEN_HANGING_SIGN);

        dropSelf(ModBlocks.OAK_HERRINGBONE);
        dropSelf(ModBlocks.SPRUCE_HERRINGBONE);
        dropSelf(ModBlocks.BIRCH_HERRINGBONE);
        dropSelf(ModBlocks.JUNGLE_HERRINGBONE);
        dropSelf(ModBlocks.ACACIA_HERRINGBONE);
        dropSelf(ModBlocks.DARK_OAK_HERRINGBONE);
        dropSelf(ModBlocks.MANGROVE_HERRINGBONE);
        dropSelf(ModBlocks.CHERRY_HERRINGBONE);
        dropSelf(ModBlocks.PALE_OAK_HERRINGBONE);
        dropSelf(ModBlocks.BAMBOO_HERRINGBONE);
        dropSelf(ModBlocks.CRIMSON_HERRINGBONE);
        dropSelf(ModBlocks.WARPED_HERRINGBONE);
        dropSelf(ModBlocks.ASPEN_HERRINGBONE);

        dropSelf(ModBlocks.OAK_MOSAIC);
        dropSelf(ModBlocks.SPRUCE_MOSAIC);
        dropSelf(ModBlocks.BIRCH_MOSAIC);
        dropSelf(ModBlocks.JUNGLE_MOSAIC);
        dropSelf(ModBlocks.ACACIA_MOSAIC);
        dropSelf(ModBlocks.DARK_OAK_MOSAIC);
        dropSelf(ModBlocks.MANGROVE_MOSAIC);
        dropSelf(ModBlocks.CHERRY_MOSAIC);
        dropSelf(ModBlocks.PALE_OAK_MOSAIC);
        dropSelf(ModBlocks.CRIMSON_MOSAIC);
        dropSelf(ModBlocks.WARPED_MOSAIC);
        dropSelf(ModBlocks.ASPEN_MOSAIC);
        dropSelf(ModBlocks.OAK_MOSAIC_STAIRS);
        dropSelf(ModBlocks.SPRUCE_MOSAIC_STAIRS);
        dropSelf(ModBlocks.BIRCH_MOSAIC_STAIRS);
        dropSelf(ModBlocks.JUNGLE_MOSAIC_STAIRS);
        dropSelf(ModBlocks.ACACIA_MOSAIC_STAIRS);
        dropSelf(ModBlocks.DARK_OAK_MOSAIC_STAIRS);
        dropSelf(ModBlocks.MANGROVE_MOSAIC_STAIRS);
        dropSelf(ModBlocks.CHERRY_MOSAIC_STAIRS);
        dropSelf(ModBlocks.PALE_OAK_MOSAIC_STAIRS);
        dropSelf(ModBlocks.CRIMSON_MOSAIC_STAIRS);
        dropSelf(ModBlocks.WARPED_MOSAIC_STAIRS);
        dropSelf(ModBlocks.ASPEN_MOSAIC_STAIRS);
        add(ModBlocks.OAK_MOSAIC_SLAB, createSlabItemTable(ModBlocks.OAK_MOSAIC_SLAB));
        add(ModBlocks.SPRUCE_MOSAIC_SLAB, createSlabItemTable(ModBlocks.SPRUCE_MOSAIC_SLAB));
        add(ModBlocks.BIRCH_MOSAIC_SLAB, createSlabItemTable(ModBlocks.BIRCH_MOSAIC_SLAB));
        add(ModBlocks.JUNGLE_MOSAIC_SLAB, createSlabItemTable(ModBlocks.JUNGLE_MOSAIC_SLAB));
        add(ModBlocks.ACACIA_MOSAIC_SLAB, createSlabItemTable(ModBlocks.ACACIA_MOSAIC_SLAB));
        add(ModBlocks.DARK_OAK_MOSAIC_SLAB, createSlabItemTable(ModBlocks.DARK_OAK_MOSAIC_SLAB));
        add(ModBlocks.MANGROVE_MOSAIC_SLAB, createSlabItemTable(ModBlocks.MANGROVE_MOSAIC_SLAB));
        add(ModBlocks.CHERRY_MOSAIC_SLAB, createSlabItemTable(ModBlocks.CHERRY_MOSAIC_SLAB));
        add(ModBlocks.PALE_OAK_MOSAIC_SLAB, createSlabItemTable(ModBlocks.PALE_OAK_MOSAIC_SLAB));
        add(ModBlocks.CRIMSON_MOSAIC_SLAB, createSlabItemTable(ModBlocks.CRIMSON_MOSAIC_SLAB));
        add(ModBlocks.WARPED_MOSAIC_SLAB, createSlabItemTable(ModBlocks.WARPED_MOSAIC_SLAB));
        add(ModBlocks.ASPEN_MOSAIC_SLAB, createSlabItemTable(ModBlocks.ASPEN_MOSAIC_SLAB));

        dropSelf(ModBlocks.WHITE_BRICKS);
        dropSelf(ModBlocks.WHITE_BRICK_STAIRS);
        add(ModBlocks.WHITE_BRICK_SLAB, createSlabItemTable(ModBlocks.WHITE_BRICK_SLAB));
        dropSelf(ModBlocks.WHITE_BRICK_WALL);
        dropSelf(ModBlocks.LIGHT_GRAY_BRICKS);
        dropSelf(ModBlocks.LIGHT_GRAY_BRICK_STAIRS);
        add(ModBlocks.LIGHT_GRAY_BRICK_SLAB, createSlabItemTable(ModBlocks.LIGHT_GRAY_BRICK_SLAB));
        dropSelf(ModBlocks.LIGHT_GRAY_BRICK_WALL);
        dropSelf(ModBlocks.GRAY_BRICKS);
        dropSelf(ModBlocks.GRAY_BRICK_STAIRS);
        add(ModBlocks.GRAY_BRICK_SLAB, createSlabItemTable(ModBlocks.GRAY_BRICK_SLAB));
        dropSelf(ModBlocks.GRAY_BRICK_WALL);
        dropSelf(ModBlocks.BLACK_BRICKS);
        dropSelf(ModBlocks.BLACK_BRICK_STAIRS);
        add(ModBlocks.BLACK_BRICK_SLAB, createSlabItemTable(ModBlocks.BLACK_BRICK_SLAB));
        dropSelf(ModBlocks.BLACK_BRICK_WALL);
        dropSelf(ModBlocks.BROWN_BRICKS);
        dropSelf(ModBlocks.BROWN_BRICK_STAIRS);
        add(ModBlocks.BROWN_BRICK_SLAB, createSlabItemTable(ModBlocks.BROWN_BRICK_SLAB));
        dropSelf(ModBlocks.BROWN_BRICK_WALL);
        dropSelf(ModBlocks.RED_BRICKS);
        dropSelf(ModBlocks.RED_BRICK_STAIRS);
        add(ModBlocks.RED_BRICK_SLAB, createSlabItemTable(ModBlocks.RED_BRICK_SLAB));
        dropSelf(ModBlocks.RED_BRICK_WALL);
        dropSelf(ModBlocks.ORANGE_BRICKS);
        dropSelf(ModBlocks.ORANGE_BRICK_STAIRS);
        add(ModBlocks.ORANGE_BRICK_SLAB, createSlabItemTable(ModBlocks.ORANGE_BRICK_SLAB));
        dropSelf(ModBlocks.ORANGE_BRICK_WALL);
        dropSelf(ModBlocks.YELLOW_BRICKS);
        dropSelf(ModBlocks.YELLOW_BRICK_STAIRS);
        add(ModBlocks.YELLOW_BRICK_SLAB, createSlabItemTable(ModBlocks.YELLOW_BRICK_SLAB));
        dropSelf(ModBlocks.YELLOW_BRICK_WALL);
        dropSelf(ModBlocks.LIME_BRICKS);
        dropSelf(ModBlocks.LIME_BRICK_STAIRS);
        add(ModBlocks.LIME_BRICK_SLAB, createSlabItemTable(ModBlocks.LIME_BRICK_SLAB));
        dropSelf(ModBlocks.LIME_BRICK_WALL);
        dropSelf(ModBlocks.GREEN_BRICKS);
        dropSelf(ModBlocks.GREEN_BRICK_STAIRS);
        add(ModBlocks.GREEN_BRICK_SLAB, createSlabItemTable(ModBlocks.GREEN_BRICK_SLAB));
        dropSelf(ModBlocks.GREEN_BRICK_WALL);
        dropSelf(ModBlocks.CYAN_BRICKS);
        dropSelf(ModBlocks.CYAN_BRICK_STAIRS);
        add(ModBlocks.CYAN_BRICK_SLAB, createSlabItemTable(ModBlocks.CYAN_BRICK_SLAB));
        dropSelf(ModBlocks.CYAN_BRICK_WALL);
        dropSelf(ModBlocks.LIGHT_BLUE_BRICKS);
        dropSelf(ModBlocks.LIGHT_BLUE_BRICK_STAIRS);
        add(ModBlocks.LIGHT_BLUE_BRICK_SLAB, createSlabItemTable(ModBlocks.LIGHT_BLUE_BRICK_SLAB));
        dropSelf(ModBlocks.LIGHT_BLUE_BRICK_WALL);
        dropSelf(ModBlocks.BLUE_BRICKS);
        dropSelf(ModBlocks.BLUE_BRICK_STAIRS);
        add(ModBlocks.BLUE_BRICK_SLAB, createSlabItemTable(ModBlocks.BLUE_BRICK_SLAB));
        dropSelf(ModBlocks.BLUE_BRICK_WALL);
        dropSelf(ModBlocks.PURPLE_BRICKS);
        dropSelf(ModBlocks.PURPLE_BRICK_STAIRS);
        add(ModBlocks.PURPLE_BRICK_SLAB, createSlabItemTable(ModBlocks.PURPLE_BRICK_SLAB));
        dropSelf(ModBlocks.PURPLE_BRICK_WALL);
        dropSelf(ModBlocks.MAGENTA_BRICKS);
        dropSelf(ModBlocks.MAGENTA_BRICK_STAIRS);
        add(ModBlocks.MAGENTA_BRICK_SLAB, createSlabItemTable(ModBlocks.MAGENTA_BRICK_SLAB));
        dropSelf(ModBlocks.MAGENTA_BRICK_WALL);
        dropSelf(ModBlocks.PINK_BRICKS);
        dropSelf(ModBlocks.PINK_BRICK_STAIRS);
        add(ModBlocks.PINK_BRICK_SLAB, createSlabItemTable(ModBlocks.PINK_BRICK_SLAB));
        dropSelf(ModBlocks.PINK_BRICK_WALL);

        dropSelf(ModBlocks.WHITE_CHERRY_SAPLING);
        dropPottedContents(ModBlocks.WHITE_CHERRY_SAPLING_POT);
        add(ModBlocks.WHITE_CHERRY_LEAVES, createLeavesDrops(ModBlocks.WHITE_CHERRY_LEAVES, ModBlocks.WHITE_CHERRY_SAPLING, 0.0625f));

        dropSelf(ModBlocks.OAK_LEAF_PILE);
        dropSelf(ModBlocks.SPRUCE_LEAF_PILE);
        dropSelf(ModBlocks.BIRCH_LEAF_PILE);
        dropSelf(ModBlocks.ASPEN_LEAF_PILE);
        dropSelf(ModBlocks.JUNGLE_LEAF_PILE);
        dropSelf(ModBlocks.ACACIA_LEAF_PILE);
        dropSelf(ModBlocks.DARK_OAK_LEAF_PILE);
        dropSelf(ModBlocks.MANGROVE_LEAF_PILE);
        dropSelf(ModBlocks.AZALEA_LEAF_PILE);
        dropSelf(ModBlocks.FLOWERING_AZALEA_LEAF_PILE);
        dropSelf(ModBlocks.CHERRY_LEAF_PILE);
        dropSelf(ModBlocks.WHITE_CHERRY_LEAF_PILE);
        dropSelf(ModBlocks.PALE_OAK_LEAF_PILE);

        dropSelf(ModBlocks.CALCITE_STAIRS);
        dropSelf(ModBlocks.SMOOTH_BASALT_STAIRS);
        add(ModBlocks.CALCITE_SLAB, createSlabItemTable(ModBlocks.CALCITE_SLAB));
        add(ModBlocks.SMOOTH_BASALT_SLAB, createSlabItemTable(ModBlocks.SMOOTH_BASALT_SLAB));
        dropSelf(ModBlocks.CALCITE_WALL);
        dropSelf(ModBlocks.SMOOTH_BASALT_WALL);
        dropSelf(ModBlocks.CALCITE_BRICKS);
        dropSelf(ModBlocks.CALCITE_TILES);
        dropSelf(ModBlocks.CHISELED_CALCITE_BRICKS);
        dropSelf(ModBlocks.SMOOTH_BASALT_BRICKS);
        dropSelf(ModBlocks.CALCITE_BRICK_STAIRS);
        dropSelf(ModBlocks.CALCITE_TILE_STAIRS);
        dropSelf(ModBlocks.SMOOTH_BASALT_BRICK_STAIRS);
        add(ModBlocks.CALCITE_BRICK_SLAB, createSlabItemTable(ModBlocks.CALCITE_BRICK_SLAB));
        add(ModBlocks.CALCITE_TILE_SLAB, createSlabItemTable(ModBlocks.CALCITE_TILE_SLAB));
        add(ModBlocks.SMOOTH_BASALT_BRICK_SLAB, createSlabItemTable(ModBlocks.SMOOTH_BASALT_BRICK_SLAB));
        dropSelf(ModBlocks.CALCITE_BRICK_WALL);
        dropSelf(ModBlocks.CALCITE_TILE_WALL);
        dropSelf(ModBlocks.SMOOTH_BASALT_BRICK_WALL);
        dropSelf(ModBlocks.POLISHED_GRANITE_WALL);
        dropSelf(ModBlocks.POLISHED_DIORITE_WALL);
        dropSelf(ModBlocks.POLISHED_ANDESITE_WALL);
        dropSelf(ModBlocks.POLISHED_GRANITE_BRICKS);
        dropSelf(ModBlocks.POLISHED_GRANITE_BRICK_STAIRS);
        add(ModBlocks.POLISHED_GRANITE_BRICK_SLAB, createSlabItemTable(ModBlocks.POLISHED_GRANITE_BRICK_SLAB));
        dropSelf(ModBlocks.POLISHED_GRANITE_BRICK_WALL);
        dropSelf(ModBlocks.POLISHED_DIORITE_BRICKS);
        dropSelf(ModBlocks.POLISHED_DIORITE_BRICK_STAIRS);
        add(ModBlocks.POLISHED_DIORITE_BRICK_SLAB, createSlabItemTable(ModBlocks.POLISHED_DIORITE_BRICK_SLAB));
        dropSelf(ModBlocks.POLISHED_DIORITE_BRICK_WALL);
        dropSelf(ModBlocks.POLISHED_ANDESITE_BRICKS);
        dropSelf(ModBlocks.POLISHED_ANDESITE_BRICK_STAIRS);
        add(ModBlocks.POLISHED_ANDESITE_BRICK_SLAB, createSlabItemTable(ModBlocks.POLISHED_ANDESITE_BRICK_SLAB));
        dropSelf(ModBlocks.POLISHED_ANDESITE_BRICK_WALL);
        dropSelf(ModBlocks.MARIGOLD);
        dropPottedContents(ModBlocks.MARIGOLD_POT);
        dropSelf(ModBlocks.VIOLET_HEATHER);
        dropSelf(ModBlocks.MAUVE_HEATHER);
        dropSelf(ModBlocks.WHITE_HEATHER);
        dropSelf(ModBlocks.AMETHYST_STAIRS);
        add(ModBlocks.AMETHYST_SLAB, createSlabItemTable(ModBlocks.AMETHYST_SLAB));
        dropSelf(ModBlocks.AMETHYST_WALL);
        dropSelf(ModBlocks.REDSTONE_LANTERN);
        dropSelf(ModBlocks.CALLIE_PLUSHIE);
        dropSelf(ModBlocks.CYNTHIA_PLUSHIE);

    }

}