package calliescrimble.picturesque.item;
import calliescrimble.picturesque.block.ModBlocks;
import net.fabricmc.fabric.api.creativetab.v1.CreativeModeTabEvents;
import net.fabricmc.fabric.api.creativetab.v1.FabricCreativeModeTabOutput;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Blocks;

public interface ModCreativeTabOutput {

    private static void addBuilding(FabricCreativeModeTabOutput output) {
        output.insertAfter(Blocks.BIRCH_BUTTON,
                ModBlocks.ASPEN_LOG,
                ModBlocks.ASPEN_WOOD,
                ModBlocks.STRIPPED_ASPEN_LOG,
                ModBlocks.STRIPPED_ASPEN_WOOD,
                ModBlocks.ASPEN_PLANKS,
                ModBlocks.ASPEN_STAIRS,
                ModBlocks.ASPEN_SLAB,
                ModBlocks.ASPEN_FENCE,
                ModBlocks.ASPEN_FENCE_GATE,
                ModBlocks.ASPEN_DOOR,
                ModBlocks.ASPEN_TRAPDOOR,
                ModBlocks.ASPEN_PRESSURE_PLATE,
                ModBlocks.ASPEN_BUTTON);
        output.insertAfter(Blocks.OAK_PLANKS,
                ModBlocks.OAK_HERRINGBONE,
                ModBlocks.OAK_MOSAIC);
        output.insertAfter(Blocks.SPRUCE_PLANKS,
                ModBlocks.SPRUCE_HERRINGBONE,
                ModBlocks.SPRUCE_MOSAIC);
        output.insertAfter(Blocks.BIRCH_PLANKS,
                ModBlocks.BIRCH_HERRINGBONE,
                ModBlocks.BIRCH_MOSAIC);
        output.insertAfter(Blocks.JUNGLE_PLANKS,
                ModBlocks.JUNGLE_HERRINGBONE,
                ModBlocks.JUNGLE_MOSAIC);
        output.insertAfter(Blocks.ACACIA_PLANKS,
                ModBlocks.ACACIA_HERRINGBONE,
                ModBlocks.ACACIA_MOSAIC);
        output.insertAfter(Blocks.DARK_OAK_PLANKS,
                ModBlocks.DARK_OAK_HERRINGBONE,
                ModBlocks.DARK_OAK_MOSAIC);
        output.insertAfter(Blocks.MANGROVE_PLANKS,
                ModBlocks.MANGROVE_HERRINGBONE,
                ModBlocks.MANGROVE_MOSAIC);
        output.insertAfter(Blocks.CHERRY_PLANKS,
                ModBlocks.CHERRY_HERRINGBONE,
                ModBlocks.CHERRY_MOSAIC);
        output.insertAfter(Blocks.PALE_OAK_PLANKS,
                ModBlocks.PALE_OAK_HERRINGBONE,
                ModBlocks.PALE_OAK_MOSAIC);
        output.insertAfter(Blocks.BAMBOO_PLANKS,
                ModBlocks.BAMBOO_HERRINGBONE);
        output.insertAfter(Blocks.CRIMSON_PLANKS,
                ModBlocks.CRIMSON_HERRINGBONE,
                ModBlocks.CRIMSON_MOSAIC);
        output.insertAfter(Blocks.WARPED_PLANKS,
                ModBlocks.WARPED_HERRINGBONE,
                ModBlocks.WARPED_MOSAIC);
        output.insertAfter(ModBlocks.ASPEN_PLANKS,
                ModBlocks.ASPEN_HERRINGBONE,
                ModBlocks.ASPEN_MOSAIC);
        output.insertAfter(Blocks.OAK_STAIRS,
                ModBlocks.OAK_MOSAIC_STAIRS);
        output.insertAfter(Blocks.OAK_SLAB,
                ModBlocks.OAK_MOSAIC_SLAB);
        output.insertAfter(Blocks.SPRUCE_STAIRS,
                ModBlocks.SPRUCE_MOSAIC_STAIRS);
        output.insertAfter(Blocks.SPRUCE_SLAB,
                ModBlocks.SPRUCE_MOSAIC_SLAB);
        output.insertAfter(Blocks.BIRCH_STAIRS,
                ModBlocks.BIRCH_MOSAIC_STAIRS);
        output.insertAfter(Blocks.BIRCH_SLAB,
                ModBlocks.BIRCH_MOSAIC_SLAB);
        output.insertAfter(Blocks.JUNGLE_STAIRS,
                ModBlocks.JUNGLE_MOSAIC_STAIRS);
        output.insertAfter(Blocks.JUNGLE_SLAB,
                ModBlocks.JUNGLE_MOSAIC_SLAB);
        output.insertAfter(Blocks.ACACIA_STAIRS,
                ModBlocks.ACACIA_MOSAIC_STAIRS);
        output.insertAfter(Blocks.ACACIA_SLAB,
                ModBlocks.ACACIA_MOSAIC_SLAB);
        output.insertAfter(Blocks.DARK_OAK_STAIRS,
                ModBlocks.DARK_OAK_MOSAIC_STAIRS);
        output.insertAfter(Blocks.DARK_OAK_SLAB,
                ModBlocks.DARK_OAK_MOSAIC_SLAB);
        output.insertAfter(Blocks.MANGROVE_STAIRS,
                ModBlocks.MANGROVE_MOSAIC_STAIRS);
        output.insertAfter(Blocks.MANGROVE_SLAB,
                ModBlocks.MANGROVE_MOSAIC_SLAB);
        output.insertAfter(Blocks.CHERRY_STAIRS,
                ModBlocks.CHERRY_MOSAIC_STAIRS);
        output.insertAfter(Blocks.CHERRY_SLAB,
                ModBlocks.CHERRY_MOSAIC_SLAB);
        output.insertAfter(Blocks.PALE_OAK_STAIRS,
                ModBlocks.PALE_OAK_MOSAIC_STAIRS);
        output.insertAfter(Blocks.PALE_OAK_SLAB,
                ModBlocks.PALE_OAK_MOSAIC_SLAB);
        output.insertAfter(Blocks.CRIMSON_STAIRS,
                ModBlocks.CRIMSON_MOSAIC_STAIRS);
        output.insertAfter(Blocks.CRIMSON_SLAB,
                ModBlocks.CRIMSON_MOSAIC_SLAB);
        output.insertAfter(Blocks.WARPED_STAIRS,
                ModBlocks.WARPED_MOSAIC_STAIRS);
        output.insertAfter(Blocks.WARPED_SLAB,
                ModBlocks.WARPED_MOSAIC_SLAB);
        output.insertAfter(ModBlocks.ASPEN_STAIRS,
                ModBlocks.ASPEN_MOSAIC_STAIRS);
        output.insertAfter(ModBlocks.ASPEN_SLAB,
                ModBlocks.ASPEN_MOSAIC_SLAB);
        output.insertAfter(Blocks.POLISHED_GRANITE_SLAB,
                ModBlocks.POLISHED_GRANITE_WALL,
                ModBlocks.POLISHED_GRANITE_BRICKS,
                ModBlocks.POLISHED_GRANITE_BRICK_STAIRS,
                ModBlocks.POLISHED_GRANITE_BRICK_SLAB,
                ModBlocks.POLISHED_GRANITE_BRICK_WALL);
        output.insertAfter(Blocks.POLISHED_DIORITE_SLAB,
                ModBlocks.POLISHED_DIORITE_WALL,
                ModBlocks.POLISHED_DIORITE_BRICKS,
                ModBlocks.POLISHED_DIORITE_BRICK_STAIRS,
                ModBlocks.POLISHED_DIORITE_BRICK_SLAB,
                ModBlocks.POLISHED_DIORITE_BRICK_WALL);
        output.insertAfter(Blocks.POLISHED_ANDESITE_SLAB,
                ModBlocks.POLISHED_ANDESITE_WALL,
                ModBlocks.POLISHED_ANDESITE_BRICKS,
                ModBlocks.POLISHED_ANDESITE_BRICK_STAIRS,
                ModBlocks.POLISHED_ANDESITE_BRICK_SLAB,
                ModBlocks.POLISHED_ANDESITE_BRICK_WALL);
        output.insertAfter(Blocks.CHISELED_TUFF_BRICKS,
                Blocks.CALCITE,
                ModBlocks.CALCITE_STAIRS,
                ModBlocks.CALCITE_SLAB,
                ModBlocks.CALCITE_WALL,
                ModBlocks.CALCITE_BRICKS,
                ModBlocks.CALCITE_BRICK_STAIRS,
                ModBlocks.CALCITE_BRICK_SLAB,
                ModBlocks.CALCITE_BRICK_WALL,
                ModBlocks.CHISELED_CALCITE_BRICKS,
                ModBlocks.CALCITE_TILES,
                ModBlocks.CALCITE_TILE_STAIRS,
                ModBlocks.CALCITE_TILE_SLAB,
                ModBlocks.CALCITE_TILE_WALL);
        output.insertAfter(Blocks.SMOOTH_BASALT,
                ModBlocks.SMOOTH_BASALT_STAIRS,
                ModBlocks.SMOOTH_BASALT_SLAB,
                ModBlocks.SMOOTH_BASALT_WALL,
                ModBlocks.SMOOTH_BASALT_BRICKS,
                ModBlocks.SMOOTH_BASALT_BRICK_STAIRS,
                ModBlocks.SMOOTH_BASALT_BRICK_SLAB,
                ModBlocks.SMOOTH_BASALT_BRICK_WALL);
        output.insertAfter(Blocks.BRICK_WALL,
                ModBlocks.WHITE_BRICKS,
                ModBlocks.WHITE_BRICK_STAIRS,
                ModBlocks.WHITE_BRICK_SLAB,
                ModBlocks.WHITE_BRICK_WALL,
                ModBlocks.LIGHT_GRAY_BRICKS,
                ModBlocks.LIGHT_GRAY_BRICK_STAIRS,
                ModBlocks.LIGHT_GRAY_BRICK_SLAB,
                ModBlocks.LIGHT_GRAY_BRICK_WALL,
                ModBlocks.GRAY_BRICKS,
                ModBlocks.GRAY_BRICK_STAIRS,
                ModBlocks.GRAY_BRICK_SLAB,
                ModBlocks.GRAY_BRICK_WALL,
                ModBlocks.BLACK_BRICKS,
                ModBlocks.BLACK_BRICK_STAIRS,
                ModBlocks.BLACK_BRICK_SLAB,
                ModBlocks.BLACK_BRICK_WALL,
                ModBlocks.BROWN_BRICKS,
                ModBlocks.BROWN_BRICK_STAIRS,
                ModBlocks.BROWN_BRICK_SLAB,
                ModBlocks.BROWN_BRICK_WALL,
                ModBlocks.RED_BRICKS,
                ModBlocks.RED_BRICK_STAIRS,
                ModBlocks.RED_BRICK_SLAB,
                ModBlocks.RED_BRICK_WALL,
                ModBlocks.ORANGE_BRICKS,
                ModBlocks.ORANGE_BRICK_STAIRS,
                ModBlocks.ORANGE_BRICK_SLAB,
                ModBlocks.ORANGE_BRICK_WALL,
                ModBlocks.YELLOW_BRICKS,
                ModBlocks.YELLOW_BRICK_STAIRS,
                ModBlocks.YELLOW_BRICK_SLAB,
                ModBlocks.YELLOW_BRICK_WALL,
                ModBlocks.LIME_BRICKS,
                ModBlocks.LIME_BRICK_STAIRS,
                ModBlocks.LIME_BRICK_SLAB,
                ModBlocks.LIME_BRICK_WALL,
                ModBlocks.GREEN_BRICKS,
                ModBlocks.GREEN_BRICK_STAIRS,
                ModBlocks.GREEN_BRICK_SLAB,
                ModBlocks.GREEN_BRICK_WALL,
                ModBlocks.CYAN_BRICKS,
                ModBlocks.CYAN_BRICK_STAIRS,
                ModBlocks.CYAN_BRICK_SLAB,
                ModBlocks.CYAN_BRICK_WALL,
                ModBlocks.LIGHT_BLUE_BRICKS,
                ModBlocks.LIGHT_BLUE_BRICK_STAIRS,
                ModBlocks.LIGHT_BLUE_BRICK_SLAB,
                ModBlocks.LIGHT_BLUE_BRICK_WALL,
                ModBlocks.BLUE_BRICKS,
                ModBlocks.BLUE_BRICK_STAIRS,
                ModBlocks.BLUE_BRICK_SLAB,
                ModBlocks.BLUE_BRICK_WALL,
                ModBlocks.PURPLE_BRICKS,
                ModBlocks.PURPLE_BRICK_STAIRS,
                ModBlocks.PURPLE_BRICK_SLAB,
                ModBlocks.PURPLE_BRICK_WALL,
                ModBlocks.MAGENTA_BRICKS,
                ModBlocks.MAGENTA_BRICK_STAIRS,
                ModBlocks.MAGENTA_BRICK_SLAB,
                ModBlocks.MAGENTA_BRICK_WALL,
                ModBlocks.PINK_BRICKS,
                ModBlocks.PINK_BRICK_STAIRS,
                ModBlocks.PINK_BRICK_SLAB,
                ModBlocks.PINK_BRICK_WALL);
        output.insertAfter(Blocks.AMETHYST_BLOCK,
                ModBlocks.AMETHYST_STAIRS,
                ModBlocks.AMETHYST_SLAB,
                ModBlocks.AMETHYST_WALL);
    }

    private static void addNatural(FabricCreativeModeTabOutput output) {
        output.insertAfter(Blocks.PALE_HANGING_MOSS,
                ModBlocks.OAK_LEAF_PILE,
                ModBlocks.SPRUCE_LEAF_PILE,
                ModBlocks.BIRCH_LEAF_PILE,
                ModBlocks.ASPEN_LEAF_PILE,
                ModBlocks.JUNGLE_LEAF_PILE,
                ModBlocks.ACACIA_LEAF_PILE,
                ModBlocks.DARK_OAK_LEAF_PILE,
                ModBlocks.MANGROVE_LEAF_PILE,
                ModBlocks.CHERRY_LEAF_PILE,
                ModBlocks.WHITE_CHERRY_LEAF_PILE,
                ModBlocks.PALE_OAK_LEAF_PILE,
                ModBlocks.AZALEA_LEAF_PILE,
                ModBlocks.FLOWERING_AZALEA_LEAF_PILE);
        output.insertAfter(Blocks.BIRCH_LOG,
                ModBlocks.ASPEN_LOG);
        output.insertAfter(Blocks.BIRCH_LEAVES,
                ModBlocks.ASPEN_LEAVES);
        output.insertAfter(Blocks.CHERRY_LEAVES,
                ModBlocks.WHITE_CHERRY_LEAVES);
        output.insertAfter(Blocks.BIRCH_SAPLING,
                ModBlocks.ASPEN_SAPLING);
        output.insertAfter(Blocks.CHERRY_SAPLING,
                ModBlocks.WHITE_CHERRY_SAPLING);
        output.insertAfter(Blocks.CORNFLOWER,
                ModBlocks.MARIGOLD);
        output.insertAfter(Blocks.LILY_OF_THE_VALLEY,
                ModBlocks.MAUVE_HEATHER,
                ModBlocks.VIOLET_HEATHER,
                ModBlocks.WHITE_HEATHER);
    }

    private static void addColored(FabricCreativeModeTabOutput output) {
        output.insertAfter(Blocks.GLAZED_TERRACOTTA.pink(),
                Blocks.BRICKS,
                Blocks.BRICK_STAIRS,
                Blocks.BRICK_SLAB,
                Blocks.BRICK_WALL);
        output.insertAfter(Blocks.BRICK_WALL,
                ModBlocks.WHITE_BRICKS,
                ModBlocks.WHITE_BRICK_STAIRS,
                ModBlocks.WHITE_BRICK_SLAB,
                ModBlocks.WHITE_BRICK_WALL);
        output.insertAfter(ModBlocks.WHITE_BRICK_WALL,
                ModBlocks.LIGHT_GRAY_BRICKS,
                ModBlocks.LIGHT_GRAY_BRICK_STAIRS,
                ModBlocks.LIGHT_GRAY_BRICK_SLAB,
                ModBlocks.LIGHT_GRAY_BRICK_WALL);
        output.insertAfter(ModBlocks.LIGHT_GRAY_BRICK_WALL,
                ModBlocks.GRAY_BRICKS,
                ModBlocks.GRAY_BRICK_STAIRS,
                ModBlocks.GRAY_BRICK_SLAB,
                ModBlocks.GRAY_BRICK_WALL);
        output.insertAfter(ModBlocks.GRAY_BRICK_WALL,
                ModBlocks.BLACK_BRICKS,
                ModBlocks.BLACK_BRICK_STAIRS,
                ModBlocks.BLACK_BRICK_SLAB,
                ModBlocks.BLACK_BRICK_WALL);
        output.insertAfter(ModBlocks.BLACK_BRICK_WALL,
                ModBlocks.BROWN_BRICKS,
                ModBlocks.BROWN_BRICK_STAIRS,
                ModBlocks.BROWN_BRICK_SLAB,
                ModBlocks.BROWN_BRICK_WALL);
        output.insertAfter(ModBlocks.BROWN_BRICK_WALL,
                ModBlocks.RED_BRICKS,
                ModBlocks.RED_BRICK_STAIRS,
                ModBlocks.RED_BRICK_SLAB,
                ModBlocks.RED_BRICK_WALL);
        output.insertAfter(ModBlocks.RED_BRICK_WALL,
                ModBlocks.ORANGE_BRICKS,
                ModBlocks.ORANGE_BRICK_STAIRS,
                ModBlocks.ORANGE_BRICK_SLAB,
                ModBlocks.ORANGE_BRICK_WALL);
        output.insertAfter(ModBlocks.ORANGE_BRICK_WALL,
                ModBlocks.YELLOW_BRICKS,
                ModBlocks.YELLOW_BRICK_STAIRS,
                ModBlocks.YELLOW_BRICK_SLAB,
                ModBlocks.YELLOW_BRICK_WALL);
        output.insertAfter(ModBlocks.YELLOW_BRICK_WALL,
                ModBlocks.LIME_BRICKS,
                ModBlocks.LIME_BRICK_STAIRS,
                ModBlocks.LIME_BRICK_SLAB,
                ModBlocks.LIME_BRICK_WALL);
        output.insertAfter(ModBlocks.LIME_BRICK_WALL,
                ModBlocks.GREEN_BRICKS,
                ModBlocks.GREEN_BRICK_STAIRS,
                ModBlocks.GREEN_BRICK_SLAB,
                ModBlocks.GREEN_BRICK_WALL);
        output.insertAfter(ModBlocks.GREEN_BRICK_WALL,
                ModBlocks.CYAN_BRICKS,
                ModBlocks.CYAN_BRICK_STAIRS,
                ModBlocks.CYAN_BRICK_SLAB,
                ModBlocks.CYAN_BRICK_WALL);
        output.insertAfter(ModBlocks.CYAN_BRICK_WALL,
                ModBlocks.LIGHT_BLUE_BRICKS,
                ModBlocks.LIGHT_BLUE_BRICK_STAIRS,
                ModBlocks.LIGHT_BLUE_BRICK_SLAB,
                ModBlocks.LIGHT_BLUE_BRICK_WALL);
        output.insertAfter(ModBlocks.LIGHT_BLUE_BRICK_WALL,
                ModBlocks.BLUE_BRICKS,
                ModBlocks.BLUE_BRICK_STAIRS,
                ModBlocks.BLUE_BRICK_SLAB,
                ModBlocks.BLUE_BRICK_WALL);
        output.insertAfter(ModBlocks.BLUE_BRICK_WALL,
                ModBlocks.PURPLE_BRICKS,
                ModBlocks.PURPLE_BRICK_STAIRS,
                ModBlocks.PURPLE_BRICK_SLAB,
                ModBlocks.PURPLE_BRICK_WALL);
        output.insertAfter(ModBlocks.PURPLE_BRICK_WALL,
                ModBlocks.MAGENTA_BRICKS,
                ModBlocks.MAGENTA_BRICK_STAIRS,
                ModBlocks.MAGENTA_BRICK_SLAB,
                ModBlocks.MAGENTA_BRICK_WALL);
        output.insertAfter(ModBlocks.MAGENTA_BRICK_WALL,
                ModBlocks.PINK_BRICKS,
                ModBlocks.PINK_BRICK_STAIRS,
                ModBlocks.PINK_BRICK_SLAB,
                ModBlocks.PINK_BRICK_WALL);
    }

    private static void addFunctional(FabricCreativeModeTabOutput output) {
        output.insertAfter(Blocks.BIRCH_SHELF, ModBlocks.ASPEN_SHELF);
        output.insertAfter(Blocks.BIRCH_HANGING_SIGN, ModItems.ASPEN_SIGN, ModItems.ASPEN_HANGING_SIGN);
        output.insertAfter(Blocks.COPPER_LANTERN.waxed().oxidized(), ModBlocks.REDSTONE_LANTERN);
        output.accept(ModBlocks.CALLIE_PLUSHIE);
        output.insertAfter(ModBlocks.CALLIE_PLUSHIE, ModBlocks.CYNTHIA_PLUSHIE);
    }

    private static void addTools(FabricCreativeModeTabOutput output) {
        output.insertAfter(Items.BIRCH_CHEST_BOAT, ModItems.ASPEN_BOAT, ModItems.ASPEN_CHEST_BOAT);
    }

    public static void initialize() {
        CreativeModeTabEvents.modifyOutputEvent(CreativeModeTabs.BUILDING_BLOCKS).register(ModCreativeTabOutput::addBuilding);
        CreativeModeTabEvents.modifyOutputEvent(CreativeModeTabs.NATURAL_BLOCKS).register(ModCreativeTabOutput::addNatural);
        CreativeModeTabEvents.modifyOutputEvent(CreativeModeTabs.COLORED_BLOCKS).register(ModCreativeTabOutput::addColored);
        CreativeModeTabEvents.modifyOutputEvent(CreativeModeTabs.FUNCTIONAL_BLOCKS).register(ModCreativeTabOutput::addFunctional);
        CreativeModeTabEvents.modifyOutputEvent(CreativeModeTabs.TOOLS_AND_UTILITIES).register(ModCreativeTabOutput::addTools);
    }

}
